SETLOCAL 

set LOGIN=-u localadmin -p Vislab1234
SET DEMOPATH=D:\demo\chahat-run\Volume_Renderer\
set START=start /MIN utilities\psexec -s -i 1 -w %DEMOPATH% %LOGIN%

SET PATH=%PATH%;D:\demo\VTK_Build\Release

SET /a SCENE_WIDTH=2560*21
SET /a SCENE_HEIGHT=6024*2
SET INSTANCE_WIDTH=2560
SET INSTANCE_HEIGHT=6024
SET PHYSICAL_HEIGHT=2.85
SET PHYSICAL_DISTANCE=2.2
SET ANGLE_TO_ROTATE=0.0
SET WEBSOCKET_HOST_IP=ws://10.10.10.98:5000/connect

::  SILO-1              DEMOPATH              SW              SH            IW                  IH          IX    IY     WX     WY            PH            PD                ANG               COL  CLID      HOST_WS_IP          GPU_ID
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  0      0      0      0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_1   %WEBSOCKET_HOST_IP%       0
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  2056   0      2056   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_2   %WEBSOCKET_HOST_IP%       1
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  5120   0      5120   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_3   %WEBSOCKET_HOST_IP%       2
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  7680   0      7680   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_4   %WEBSOCKET_HOST_IP%       3
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  0      6024   0      6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_5   %WEBSOCKET_HOST_IP%       4
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  2056   6024   2056   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_6   %WEBSOCKET_HOST_IP%       5
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  5120   6024   5120   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_7   %WEBSOCKET_HOST_IP%       6
%START% \\SILO-1 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  7680   6024   7680   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_8   %WEBSOCKET_HOST_IP%       7

::  SILO-2              DEMOPATH              SW              SH            IW                  IH          IX     IY     WX     WY            PH            PD                ANG               COL  CLID      HOST_WS_IP          GPU_ID
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  10240  0      0      0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_1   %WEBSOCKET_HOST_IP%       0
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  12800  0      2056   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_2   %WEBSOCKET_HOST_IP%       1
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  15360  0      5120   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_3   %WEBSOCKET_HOST_IP%       2
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  17920  0      7680   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_4   %WEBSOCKET_HOST_IP%       3
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  10240  6024   0      6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_5   %WEBSOCKET_HOST_IP%       4
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  12800  6024   2056   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_6   %WEBSOCKET_HOST_IP%       5
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  15360  6024   5120   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_7   %WEBSOCKET_HOST_IP%       6
%START% \\SILO-2 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  17920  6024   7680   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_8   %WEBSOCKET_HOST_IP%       7

::  SILO-3              DEMOPATH              SW              SH            IW                  IH          IX    IY     WX     WY            PH            PD                ANG               COL  CLID      HOST_WS_IP          GPU_ID
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  20480  0      0      0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_1   %WEBSOCKET_HOST_IP%       0
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  23040  0      2056   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_2   %WEBSOCKET_HOST_IP%       1
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  25600  0      5120   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_3   %WEBSOCKET_HOST_IP%       2
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  28160  0      7680   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_4   %WEBSOCKET_HOST_IP%       3
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  20480  6024   0      6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_5   %WEBSOCKET_HOST_IP%       4
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  23040  6024   2056   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_6   %WEBSOCKET_HOST_IP%       5
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  25600  6024   5120   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_7   %WEBSOCKET_HOST_IP%       6
%START% \\SILO-3 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  28160  6024   7680   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_8   %WEBSOCKET_HOST_IP%       7

::  SILO-4              DEMOPATH              SW              SH            IW                  IH          IX    IY     WX     WY            PH            PD                ANG               COL  CLID      HOST_WS_IP          GPU_ID
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  30720  0      0      0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_1   %WEBSOCKET_HOST_IP%       0
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  33280  0      2056   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_2   %WEBSOCKET_HOST_IP%       1
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  35840  0      5120   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_3   %WEBSOCKET_HOST_IP%       2
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  38400  0      7680   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_4   %WEBSOCKET_HOST_IP%       3
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  30720  6024   0      6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_5   %WEBSOCKET_HOST_IP%       4
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  33280  6024   2056   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_6   %WEBSOCKET_HOST_IP%       5
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  35840  6024   5120   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_7   %WEBSOCKET_HOST_IP%       6
%START% \\SILO-4 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  38400  6024   7680   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_8   %WEBSOCKET_HOST_IP%       7

::  SILO-5              DEMOPATH              SW              SH            IW                  IH          IX    IY     WX     WY            PH            PD                ANG               COL  CLID      HOST_WS_IP          GPU_ID
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  40960  0      0      0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_1   %WEBSOCKET_HOST_IP%       0
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  43520  0      2056   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_2   %WEBSOCKET_HOST_IP%       1
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  46080  0      5120   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_3   %WEBSOCKET_HOST_IP%       2
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  48640  0      7680   0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_4   %WEBSOCKET_HOST_IP%       3
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  40960  6024   0      6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_5   %WEBSOCKET_HOST_IP%       4
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  43520  6024   2056   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_6   %WEBSOCKET_HOST_IP%       5
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  46080  6024   5120   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   0   3_7   %WEBSOCKET_HOST_IP%       6
%START% \\SILO-5 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  48640  6024   7680   6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%   1   3_8   %WEBSOCKET_HOST_IP%       7

::  SILO-6              DEMOPATH              SW              SH            IW                  IH          IX    IY     WX     WY            PH            PD                ANG               COL  CLID      HOST_WS_IP          GPU_ID
%START% \\SILO-6 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  51200  0      0      0     %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -2   3_1   %WEBSOCKET_HOST_IP%       0
%START% \\SILO-6 %DEMOPATH%\VTK_Engine.exe %SCENE_WIDTH% %SCENE_HEIGHT% %INSTANCE_WIDTH% %INSTANCE_HEIGHT%  51200  6024   0      6024  %PHYSICAL_HEIGHT% %PHYSICAL_DISTANCE% %ANGLE_TO_ROTATE%  -1   3_2   %WEBSOCKET_HOST_IP%       1
